default: &default
  pid_file: <%= Rails.root.join('tmp', 'pids', "#{Rails.env}.searchd.pid") %>
  min_infix_len: 3


test:
  <<: *default
  mysql41: 9307

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
